version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    ports:
    - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  edge:
    image: selenium/node-edge:4.1.0
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  myinsurance:
    image: jadyjdjady1990/cts-docker
    depends_on:
      - chrome
      - edge
    volumes:
      - C:\mydockerdata\channels\result:/usr/share/digital/extent-test-output